global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.xx.com:xx'
  smtp_from: 'xx@xx.com'
  smtp_auth_username: 'xx@xx.com'
  smtp_auth_password: 'xxx'
  smtp_require_tls: false
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
    - match:
        severity: critical
      receiver: 'leader'
      continue: true
    - match_re:
        severity: ^(warning|critical)$
      receiver: 'devops'
      continue: true
receivers:
- name: 'email'
  email_configs:
  - to: 'xx@xx.com'
    html: '{{ template "email.to.html" . }}' ##使用模板的方式发送
    send_resolved: true
- name: 'wechat'
  wechat_configs:
    - corp_id: 'XX'
      to_party: '1'
      agent_id: 'XX'
      api_secret: 'XX'
      send_resolved: true
      message: '{{ template "wechat.tmpl" . }}'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']