labels:
  severity: warning
- source_match:
    severity: 'critical' ###严重等级，发给 leader
  target_match:
    severity: 'warning' ###一般告警，发给普通运维开发即可
routes:
  - match:
      severity: critical
    receiver: 'leader'
    continue: true
  - match_re:
      severity: ^(warning|critical)$
    receiver: 'devops'
    continue: true

receivers:
  - name: 'wechat'
    wechat_configs:
  - corp_id: 'wwf4ee8ede83b63a1a'
    to_party: '1'
    agent_id: 'xx'
    api_secret: 'xx'
    send_resolved: true
    message: '{{ template "wechat.tmpl" . }}

route:
  group_by: [severity]