logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    pers.ervin: debug
spring:
  rabbitmq:
    host: 192.168.150.101 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: root
    password: root001
    virtual-host: /
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    template:
#      mandatory: true